import { pgSchema, text, timestamp, uuid } from "drizzle-orm/pg-core";

// The widgets module's tables, in a Postgres schema named after the module (WP-10 "Postgres schema
// per module"). Only this module's infrastructure/ reads them: never exported from the module's
// index.ts, so other modules cannot reach the table (rule modules-import-through-index). A service
// that copies the module lets its drizzle.config.ts glob (src/modules/*/infrastructure/*.schema.ts)
// pick this file up, then `db:generate` writes the migration.

/**
 * The `widgets` Postgres schema. Exported because drizzle-kit writes `CREATE SCHEMA` only for a
 * schema value it finds among a config's exports.
 */
export const widgetsSchema = pgSchema("widgets");

/** One row per widget (`widgets.widgets`); column names in snake_case through Drizzle's `casing`. */
export const widgets = widgetsSchema.table("widgets", {
  /** Generated by the application through the `IdGenerator` port, not by Postgres. */
  id: uuid().primaryKey(),
  /** Length is a domain rule (1 to 60 characters), so the column is plain `text`. */
  name: text().notNull(),
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
});
