import { generateDrizzleJson, generateMigration } from "drizzle-kit/api";
import * as schema from "../../src/modules/widgets/infrastructure/widget.schema.js";

/**
 * The DDL of the widgets module's schema file from an empty database, generated by drizzle-kit's
 * own diff, the one `db:generate` runs in a service that copies the module. The template has no
 * migration folder (it is never deployed), so its tests build the table from the schema file:
 * what the contract suites run against is always what a service would generate. The same approach
 * as `packages/messaging/test/support/messaging-ddl.ts`.
 * @returns the statements, in the order drizzle-kit writes them.
 */
export async function widgetsDdl(): Promise<string[]> {
  const empty = generateDrizzleJson({});
  const current = generateDrizzleJson(schema, empty.id, undefined, "snake_case");
  return generateMigration(empty, current);
}
