import { generateDrizzleJson, generateMigration } from "drizzle-kit/api";
import * as schema from "../../src/schema.js";

/**
 * The DDL of `@jadero/messaging/schema` (both tables) from an empty database, generated by
 * drizzle-kit's own diff, the one `db:generate` runs in each service. The package has no migration
 * folder of its own (each service owns its migrations, WP-10 Q1 A), so its tests build the tables
 * from the schema they export: what the package tests is always what the services generate.
 * @returns the statements, in the order drizzle-kit writes them.
 */
export async function messagingDdl(): Promise<string[]> {
  const empty = generateDrizzleJson({});
  const current = generateDrizzleJson(schema, empty.id, undefined, "snake_case");
  return generateMigration(empty, current);
}
